# This is a basic workflow to help you get started with Actions

name: 自动部署 Hexo

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ hexo_source ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 开始运行
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: 设置 Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # Runs a set of commands using the runners shell
      - name: 配置 Git 环境
        env:
          ACTION_DEPLOY_KEY: ${{secrets.ACTION_DEPLOY_KEY}}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name "zqhjl"
          git config --global user.email "hjlcarl@163.com"

      - name: 安装 Hexo CI
        run: |
          export TZ='Asia/Shanghai'
          npm i -g hexo-cli
          npm i

      # bulma-stylus@0.8.0 --save
          # npm install disqusjs --save
          # npm install hexo --save
          # npm install hexo-component-inferno@0.10.3 --save
          # npm install hexo-deployer-git --save
          # npm install hexo-generator-archive --save
          # npm install hexo-generator-category --save
          # npm install hexo-generator-index --save
          # npm install hexo-generator-tag --save
          # npm install hexo-renderer-ejs --save
          # npm install hexo-renderer-inferno --save
          # npm install hexo-renderer-marked --save
          # npm install hexo-server --save
          # npm install hexo-theme-icarus --save
      - name: 安装插件
        run: |
          npm install
          

      - name: 部署博客
        run: |
          hexo clean
          hexo d -g
